# Dictionaries containing variable parameters for ABCD regions and systematics
isRegionA = {
              'ht' : {
                       'Wts'   : 'EvtWeight*EvtWtPV*QuadWeightHT(ht,0)',
                       'Wts_topSFUp'   : 'EvtWeight*EvtWtPV*QuadWeightHT(ht,0)',
                       'Wts_topSFDown'   : 'EvtWeight*EvtWtPV*QuadWeightHT(ht,0)',
                       'Wts_bcUp'   : 'EvtWeight*EvtWtPV*btagsf_bcUp*QuadWeightHT(ht,0)',
                       'Wts_bcDown'   : 'EvtWeight*EvtWtPV*btagsf_bcDown*QuadWeightHT(ht,0)',
                       'Wts_lUp'   : 'EvtWeight*EvtWtPV*btagsf_lUp*QuadWeightHT(ht,0)',
                       'Wts_lDown'   : 'EvtWeight*EvtWtPV*btagsf_lDown*QuadWeightHT(ht,0)',
                       'Wts_HTUp'   : 'EvtWeight*EvtWtPV*QuadWeightHT(ht,1)',
                       'Wts_HTDown'   : 'EvtWeight*EvtWtPV*QuadWeightHT(ht,-1)',
                       'Wts_mufUp'   : 'EvtWeight*EvtWtPV*SelectedEvent_lhewts.second[2]*QuadWeightHT(ht,0)',
                       'Wts_mufDown'   : 'EvtWeight*EvtWtPV*SelectedEvent_lhewts.second[3]*QuadWeightHT(ht,0)',
                       'Wts_murUp'   : 'EvtWeight*EvtWtPV*SelectedEvent_lhewts.second[4]*QuadWeightHT(ht,0)',
                       'Wts_murDown'   : 'EvtWeight*EvtWtPV*SelectedEvent_lhewts.second[7]*QuadWeightHT(ht,0)',
                       'SigWts' : 'EvtWeight*EvtWtPV',
                       'SigWts_topSFUp' : 'EvtWeight*EvtWtPV',
                       'SigWts_topSFDown' : 'EvtWeight*EvtWtPV',
                       'SigWts_bcUp'   : 'EvtWeight*EvtWtPV*btagsf_bcUp',
                       'SigWts_bcDown'   : 'EvtWeight*EvtWtPV*btagsf_bcDown',
                       'SigWts_lUp'   : 'EvtWeight*EvtWtPV*btagsf_lUp',
                       'SigWts_lDown'   : 'EvtWeight*EvtWtPV*btagsf_lDown',
                       'SigWts_HTUp'   : 'EvtWeight*EvtWtPV',
                       'SigWts_HTDown'   : 'EvtWeight*EvtWtPV',
                       'SigWts_mufUp'   : 'EvtWeight*EvtWtPV*SelectedEvent_lhewts.second[2]',
                       'SigWts_mufDown'   : 'EvtWeight*EvtWtPV*SelectedEvent_lhewts.second[3]',
                       'SigWts_murUp'   : 'EvtWeight*EvtWtPV*SelectedEvent_lhewts.second[4]',
                       'SigWts_murDown'   : 'EvtWeight*EvtWtPV*SelectedEvent_lhewts.second[7]',
                       #'Cuts'  : 'nAK8>=2 && ptAK8[idxAK8[0]]>500 && ptAK8[idxAK8[1]]>300 && (idxAK8 == idxAK8[0] || idxAK8 == idxAK8[1]) && ht>1100&&(@idxHTagged.size()==0&&@idxAntiHTagged.size()>0&&@idxTopTagged.size()==0)&&Max$(abs(etaAK4))>1.5',
                       'Cuts'  : 'nAK8>=2 && ptAK8[idxAK8[0]]>400 && ptAK8[idxAK8[1]]>300 && (idxAK8[0] == idxAntiHTagged || idxAK8[1] == idxAntiHTagged) && ht>1100 && isRegionA && ptAntiHTagged > 300',
                       'xMin'  : '1100',
                       'xMax'  : '3200',
                       'nBins' : '50',
                       'xLabel' : 'H_{T} [GeV]',
                       'yLabel' : 'Events/80GeV',
                       'log'   : True
                     }
            }
isRegionA_mt = {
              'mtprimeDummyA' : {
                       'Wts'   : 'EvtWeight*EvtWtPV*btagsf',
                       'Wts_topSFUp'   : 'EvtWeight*EvtWtPV*QuadWeightHT(ht,0)*topSFUp(ptAntiTopTagged)',
                       'Wts_topSFDown'   : 'EvtWeight*EvtWtPV*QuadWeightHT(ht,0)*topSFDown(ptAntiTopTagged)',
                       'Wts_bcUp'   : 'EvtWeight*EvtWtPV*btagsf_bcUp*btagsf',
                       'Wts_bcDown'   : 'EvtWeight*EvtWtPV*btagsf_bcDown*btagsf',
                       'Wts_lUp'   : 'EvtWeight*EvtWtPV*btagsf_lUp*btagsf',
                       'Wts_lDown'   : 'EvtWeight*EvtWtPV*btagsf_lDown*btagsf',
                       'Wts_HTUp'   : 'EvtWeight*EvtWtPV*QuadWeightHT(ht,1)*topSF(ptAntiTopTagged)',
                       'Wts_HTDown'   : 'EvtWeight*EvtWtPV*QuadWeightHT(ht,-1)*topSF(ptAntiTopTagged)',
                       'Wts_mufUp'   : 'EvtWeight*EvtWtPV*SelectedEvent_lhewts.second[2]*btagsf',
                       'Wts_mufDown'   : 'EvtWeight*EvtWtPV*SelectedEvent_lhewts.second[3]*btagsf',
                       'Wts_murUp'   : 'EvtWeight*EvtWtPV*SelectedEvent_lhewts.second[4]*btagsf',
                       'Wts_murDown'   : 'EvtWeight*EvtWtPV*SelectedEvent_lhewts.second[7]*btagsf',
                       'SigWts' : 'EvtWeight*EvtWtPV*topSF(ptAntiTopTagged)',
                       'SigWts_topSFUp' : 'EvtWeight*EvtWtPV*topSFUp(ptAntiTopTagged)',
                       'SigWts_topSFDown' : 'EvtWeight*EvtWtPV*topSFDown(ptAntiTopTagged)',
                       'SigWts_bcUp'   : 'EvtWeight*EvtWtPV*btagsf_bcUp*topSF(ptAntiTopTagged)',
                       'SigWts_bcDown'   : 'EvtWeight*EvtWtPV*btagsf_bcDown*topSF(ptAntiTopTagged)',
                       'SigWts_lUp'   : 'EvtWeight*EvtWtPV*btagsf_lUp*topSF(ptAntiTopTagged)',
                       'SigWts_lDown'   : 'EvtWeight*EvtWtPV*btagsf_lDown*topSF(ptAntiTopTagged)',
                       'SigWts_HTUp'   : 'EvtWeight*EvtWtPV*topSF(ptAntiTopTagged)',
                       'SigWts_HTDown'   : 'EvtWeight*EvtWtPV*topSF(ptAntiTopTagged)',
                       'SigWts_mufUp'   : 'EvtWeight*EvtWtPV*SelectedEvent_lhewts.second[2]*topSF(ptAntiTopTagged)',
                       'SigWts_mufDown'   : 'EvtWeight*EvtWtPV*SelectedEvent_lhewts.second[3]*topSF(ptAntiTopTagged)',
                       'SigWts_murUp'   : 'EvtWeight*EvtWtPV*SelectedEvent_lhewts.second[4]*topSF(ptAntiTopTagged)',
                       'SigWts_murDown'   : 'EvtWeight*EvtWtPV*SelectedEvent_lhewts.second[7]*topSF(ptAntiTopTagged)',
                       #'Cuts'  : 'nAK8>=2 && ptAK8[idxAK8[0]]>500 && ptAK8[idxAK8[1]]>300 && (idxAK8 == idxAK8[0] || idxAK8 == idxAK8[1]) && ht>1100&&(@idxHTagged.size()==0&&@idxAntiHTagged.size()>0&&@idxTopTagged.size()==0)&&Max$(abs(etaAK4))>1.5',
                       #'Cuts'  : 'nAK8>=2 && ptAK8[idxAK8[0]]>400 && ptAK8[idxAK8[1]]>200 && (idxAK8[0] == idxAntiHTagged || idxAK8[1] == idxAntiHTagged) && ht>1100 && isRegionA && ptAntiHTagged > 300',
                       'Cuts'  : '(ptAK8[0]+ptAK8[1])>850 &&nAK8>=2 && ptAK8[idxAK8[0]]>400 && PrunedMassAK8[0]>50 && isRegionA',
                       'xMin'  : '600',
                       'xMax'  : '2400',
                       'nBins' : '36',
                       'xLabel' : 'M_{T} [GeV]',
                       'yLabel' : 'Events/50GeV',
                       'log'   : True
                     }
            }
isRegionB = {
              'ht' : {
                       'Wts'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*QuadWeightHT(ht,0)',
                       'Wts_topSFUp'   : 'EvtWeight*EvtWtPV*topSFUp(ptTopTagged)*QuadWeightHT(ht,0)',
                       'Wts_topSFDown'   : 'EvtWeight*EvtWtPV*topSFDown(ptTopTagged)*QuadWeightHT(ht,0)',
                       'Wts_bcUp'   : 'EvtWeight*EvtWtPV*btagsf_bcUp*topSF(ptTopTagged)*QuadWeightHT(ht,0)',
                       'Wts_bcDown'   : 'EvtWeight*EvtWtPV*btagsf_bcDown*topSF(ptTopTagged)*QuadWeightHT(ht,0)',
                       'Wts_lUp'   : 'EvtWeight*EvtWtPV*btagsf_lUp*topSF(ptTopTagged)*QuadWeightHT(ht,0)',
                       'Wts_lDown'   : 'EvtWeight*EvtWtPV*btagsf_lDown*topSF(ptTopTagged)*QuadWeightHT(ht,0)',
                       'Wts_HTUp'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*QuadWeightHT(ht,1)',
                       'Wts_HTDown'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*QuadWeightHT(ht,-1)',
                       'Wts_mufUp'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*QuadWeightHT(ht,0)*SelectedEvent_lhewts.second[2]',
                       'Wts_mufDown'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*QuadWeightHT(ht,0)*SelectedEvent_lhewts.second[3]',
                       'Wts_murUp'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*QuadWeightHT(ht,0)*SelectedEvent_lhewts.second[4]',
                       'Wts_murDown'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*QuadWeightHT(ht,0)*SelectedEvent_lhewts.second[7]',
                       'SigWts' : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*QuadWeightHT(ht,0)',
                       'SigWts_topSFUp'   : 'EvtWeight*EvtWtPV*topSFUp(ptTopTagged)',
                       'SigWts_topSFDown'   : 'EvtWeight*EvtWtPV*topSFDown(ptTopTagged)',
                       'SigWts_bcUp' : 'EvtWeight*EvtWtPV*btagsf_bcUp*topSF(ptTopTagged)',
                       'SigWts_bcDown' : 'EvtWeight*EvtWtPV*btagsf_bcDown*topSF(ptTopTagged)',
                       'SigWts_lUp' : 'EvtWeight*EvtWtPV*btagsf_lUp*topSF(ptTopTagged)',
                       'SigWts_lDown' : 'EvtWeight*EvtWtPV*btagsf_lDown*topSF(ptTopTagged)',
                       'SigWts_HTUp'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)',
                       'SigWts_HTDown'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)',
                       'SigWts_mufUp'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*SelectedEvent_lhewts.second[2]',
                       'SigWts_mufDown'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*SelectedEvent_lhewts.second[3]',
                       'SigWts_murUp'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*SelectedEvent_lhewts.second[4]',
                       'SigWts_murDown'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*SelectedEvent_lhewts.second[7]',
                       #'Cuts'  : 'nAK8>=2 && ptAK8[idxAK8[0]]>500 && ptAK8[idxAK8[1]]>300 && (idxAK8 == idxAK8[0] || idxAK8 == idxAK8[1]) && ht>1100&&(@idxHTagged.size()==0&&@idxAntiHTagged.size()>0&&@idxTopTagged.size()>0)&&isRegionB&&Max$(abs(etaAK4))>1.5',
                       'Cuts'  : 'nAK8>=2 && ptAK8[idxAK8[0]]>400 && ptAK8[idxAK8[1]]>300 && (idxAK8[0] == idxAntiHTagged && idxAK8[1] == idxTopTagged) || (idxAK8[1] == idxAntiHTagged && idxAK8[0] == idxTopTagged) && ht>1100&&isRegionB && ptAntiHTagged > 300',
                       'xMin'  : '1100',
                       'xMax'  : '3200',
                       'nBins' : '50',
                       'xLabel' : 'H_{T} [GeV]',
                       'yLabel' : 'Events/80GeV',
                       'log'   : True
                     }
               }
isRegionB_mt = {
              'mtprimeDummy' : {
                       'Wts'   : 'EvtWeight*EvtWtPV*btagsf',
                       'Wts_topSFUp'   : 'EvtWeight*EvtWtPV*topSFUp(ptTopTagged)*QuadWeightHT(ht,0)',
                       'Wts_topSFDown'   : 'EvtWeight*EvtWtPV*topSFDown(ptTopTagged)*QuadWeightHT(ht,0)',
                       'Wts_bcUp'   : 'EvtWeight*EvtWtPV*btagsf_bcUp*topSF(ptTopTagged)*QuadWeightHT(ht,0)',
                       'Wts_bcDown'   : 'EvtWeight*EvtWtPV*btagsf_bcDown*topSF(ptTopTagged)*QuadWeightHT(ht,0)',
                       'Wts_lUp'   : 'EvtWeight*EvtWtPV*btagsf_lUp*topSF(ptTopTagged)*QuadWeightHT(ht,0)',
                       'Wts_lDown'   : 'EvtWeight*EvtWtPV*btagsf_lDown*topSF(ptTopTagged)*QuadWeightHT(ht,0)',
                       'Wts_HTUp'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*QuadWeightHT(ht,1)',
                       'Wts_HTDown'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*QuadWeightHT(ht,-1)',
                       'Wts_mufUp'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*QuadWeightHT(ht,0)*SelectedEvent_lhewts.second[2]',
                       'Wts_mufDown'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*QuadWeightHT(ht,0)*SelectedEvent_lhewts.second[3]',
                       'Wts_murUp'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*QuadWeightHT(ht,0)*SelectedEvent_lhewts.second[4]',
                       'Wts_murDown'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*QuadWeightHT(ht,0)*SelectedEvent_lhewts.second[7]',
                       'SigWts' : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)',
                       'SigWts_topSFUp'   : 'EvtWeight*EvtWtPV*topSFUp(ptTopTagged)',
                       'SigWts_topSFDown'   : 'EvtWeight*EvtWtPV*topSFDown(ptTopTagged)',
                       'SigWts_bcUp' : 'EvtWeight*EvtWtPV*btagsf_bcUp*topSF(ptTopTagged)',
                       'SigWts_bcDown' : 'EvtWeight*EvtWtPV*btagsf_bcDown*topSF(ptTopTagged)',
                       'SigWts_lUp' : 'EvtWeight*EvtWtPV*btagsf_lUp*topSF(ptTopTagged)',
                       'SigWts_lDown' : 'EvtWeight*EvtWtPV*btagsf_lDown*topSF(ptTopTagged)',
                       'SigWts_HTUp'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)',
                       'SigWts_HTDown'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)',
                       'SigWts_mufUp'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*SelectedEvent_lhewts.second[2]',
                       'SigWts_mufDown'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*SelectedEvent_lhewts.second[3]',
                       'SigWts_murUp'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*SelectedEvent_lhewts.second[4]',
                       'SigWts_murDown'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*SelectedEvent_lhewts.second[7]',
                       #'Cuts'  : 'nAK8>=2 && ptAK8[idxAK8[0]]>400 && ptAK8[idxAK8[1]]>300 && (idxAK8[0] == idxAntiHTagged && idxAK8[1] == idxTopTagged) || (idxAK8[1] == idxAntiHTagged && idxAK8[0] == idxTopTagged) && ht>1100&&isRegionB && ptAntiHTagged > 300',
#                       'Cuts'  : 'nAK8>=2 && ptAK8[idxAK8[0]]>400 && ptAK8[idxAK8[1]]>200 && @idxHTagged.size()==0 && @idxAntiHTagged.size()>0 && @idxTopTagged.size()>0 && ptTopTagged>400&&(tau3TopTagged/tau2TopTagged)<0.5&&SoftDropMassTopTagged<220&&SoftDropMassTopTagged>=105&&max(sj0CSVTopTagged,sj1CSVTopTagged)>=0.460 && dR(etaAntiHTagged,phiAntiHTagged,etaTopTagged,phiTopTagged)>2.0',
                       'Cuts'  : '(ptAK8[0]+ptAK8[1])>850 &&nAK8>=2 && ptAK8[idxAK8[0]]>400 && PrunedMassAK8[0]>50 && isRegionB',
                       'xMin'  : '600',
                       'xMax'  : '2400',
                       'nBins' : '36',
                       'xLabel' : 'M_{T} [GeV]',
                       'yLabel' : 'Events/50GeV',
                       'log'   : True
                     }
            }
isRegionC = {
              'ht' : {
                       'Wts'   : 'EvtWeight*EvtWtPV*QuadWeightHT(ht,0)',
                       'Wts_topSFUp'   : 'EvtWeight*EvtWtPV*QuadWeightHT(ht,0)',
                       'Wts_topSFDown'   : 'EvtWeight*EvtWtPV*QuadWeightHT(ht,0)',
                       'Wts_bcUp'   : 'EvtWeight*EvtWtPV*btagsf_bcUp*QuadWeightHT(ht,0)',
                       'Wts_bcDown'   : 'EvtWeight*EvtWtPV*btagsf_bcDown*QuadWeightHT(ht,0)',
                       'Wts_lUp'   : 'EvtWeight*EvtWtPV*btagsf_lUp*QuadWeightHT(ht,0)',
                       'Wts_lDown'   : 'EvtWeight*EvtWtPV*btagsf_lDown*QuadWeightHT(ht,0)',
                       'Wts_HTUp'   : 'EvtWeight*EvtWtPV*QuadWeightHT(ht,1)',
                       'Wts_HTDown'   : 'EvtWeight*EvtWtPV*QuadWeightHT(ht,-1)',
                       'Wts_mufUp'   : 'EvtWeight*EvtWtPV*SelectedEvent_lhewts.second[2]*QuadWeightHT(ht,0)',
                       'Wts_mufDown'   : 'EvtWeight*EvtWtPV*SelectedEvent_lhewts.second[3]*QuadWeightHT(ht,0)',
                       'Wts_murUp'   : 'EvtWeight*EvtWtPV*SelectedEvent_lhewts.second[4]*QuadWeightHT(ht,0)',
                       'Wts_murDown'   : 'EvtWeight*EvtWtPV*SelectedEvent_lhewts.second[7]*QuadWeightHT(ht,0)',
                       'SigWts' : 'EvtWeight*EvtWtPV',
                       'SigWts_topSFUp'   : 'EvtWeight*EvtWtPV',
                       'SigWts_topSFDown'   : 'EvtWeight*EvtWtPV',
                       'SigWts_bcUp'   : 'EvtWeight*EvtWtPV*btagsf_bcUp',
                       'SigWts_bcDown'   : 'EvtWeight*EvtWtPV*btagsf_bcDown',
                       'SigWts_lUp'   : 'EvtWeight*EvtWtPV*btagsf_lUp',
                       'SigWts_lDown'   : 'EvtWeight*EvtWtPV*btagsf_lDown',
                       'SigWts_HTUp'   : 'EvtWeight*EvtWtPV',
                       'SigWts_HTDown'   : 'EvtWeight*EvtWtPV',
                       'SigWts_mufUp'   : 'EvtWeight*EvtWtPV*SelectedEvent_lhewts.second[2]',
                       'SigWts_mufDown'   : 'EvtWeight*EvtWtPV*SelectedEvent_lhewts.second[3]',
                       'SigWts_murUp'   : 'EvtWeight*EvtWtPV*SelectedEvent_lhewts.second[4]',
                       'SigWts_murDown'   : 'EvtWeight*EvtWtPV*SelectedEvent_lhewts.second[7]',
                       #'Cuts'  : 'nAK8>=2 && ptAK8[idxAK8[0]]>500 && ptAK8[idxAK8[1]]>300 && (idxAK8 == idxAK8[0] || idxAK8 == idxAK8[1]) && ht>1100&&(@idxHTagged.size()>0&&@idxAntiHTagged.size()>=0&&@idxTopTagged.size()==0)&&isRegionC&&Max$(abs(etaAK4))>1.5',
                       'Cuts'  : 'nAK8>=2 && ptAK8[idxAK8[0]]>400 && ptAK8[idxAK8[1]]>300 && (idxAK8[0] == idxHTagged || idxAK8[1] == idxHTagged)  && ht>1100&&isRegionC ',
                       'xMin'  : '1100',
                       'xMax'  : '3200',
                       'nBins' : '50',
                       'xLabel' : 'H_{T} [GeV]',
                       'yLabel' : 'Events/80GeV',
                       'log'   : True
                     }
            }
isRegionC_mt = {
              'mtprimeDummyC' : {
                       'Wts'   : 'EvtWeight*EvtWtPV*btagsf',
                       'Wts_topSFUp'   : 'EvtWeight*EvtWtPV*QuadWeightHT(ht,0)*topSFUp(ptAntiTopTagged)',
                       'Wts_topSFDown'   : 'EvtWeight*EvtWtPV*QuadWeightHT(ht,0)*topSFDown(ptAntiTopTagged)',
                       'Wts_bcUp'   : 'EvtWeight*EvtWtPV*btagsf_bcUp*btagsf',
                       'Wts_bcDown'   : 'EvtWeight*EvtWtPV*btagsf_bcDown*btagsf',
                       'Wts_lUp'   : 'EvtWeight*EvtWtPV*btagsf_lUp*btagsf',
                       'Wts_lDown'   : 'EvtWeight*EvtWtPV*btagsf_lDown*btagsf',
                       'Wts_HTUp'   : 'EvtWeight*EvtWtPV*QuadWeightHT(ht,1)*topSF(ptAntiTopTagged)',
                       'Wts_HTDown'   : 'EvtWeight*EvtWtPV*QuadWeightHT(ht,-1)*topSF(ptAntiTopTagged)',
                       'Wts_mufUp'   : 'EvtWeight*EvtWtPV*SelectedEvent_lhewts.second[2]*btagsf',
                       'Wts_mufDown'   : 'EvtWeight*EvtWtPV*SelectedEvent_lhewts.second[3]*btagsf',
                       'Wts_murUp'   : 'EvtWeight*EvtWtPV*SelectedEvent_lhewts.second[4]*btagsf',
                       'Wts_murDown'   : 'EvtWeight*EvtWtPV*SelectedEvent_lhewts.second[7]*btagsf',
                       'SigWts' : 'EvtWeight*EvtWtPV*topSF(ptAntiTopTagged)',
                       'SigWts_topSFUp'   : 'EvtWeight*EvtWtPV*topSFUp(ptAntiTopTagged)',
                       'SigWts_topSFDown'   : 'EvtWeight*EvtWtPV*topSFDown(ptAntiTopTagged)',
                       'SigWts_bcUp'   : 'EvtWeight*EvtWtPV*btagsf_bcUp*topSF(ptAntiTopTagged)',
                       'SigWts_bcDown'   : 'EvtWeight*EvtWtPV*btagsf_bcDown*topSF(ptAntiTopTagged)',
                       'SigWts_lUp'   : 'EvtWeight*EvtWtPV*btagsf_lUp*topSF(ptAntiTopTagged)',
                       'SigWts_lDown'   : 'EvtWeight*EvtWtPV*btagsf_lDown*topSF(ptAntiTopTagged)',
                       'SigWts_HTUp'   : 'EvtWeight*EvtWtPV*topSF(ptAntiTopTagged)',
                       'SigWts_HTDown'   : 'EvtWeight*EvtWtPV*topSF(ptAntiTopTagged)',
                       'SigWts_mufUp'   : 'EvtWeight*EvtWtPV*SelectedEvent_lhewts.second[2]*topSF(ptAntiTopTagged)',
                       'SigWts_mufDown'   : 'EvtWeight*EvtWtPV*SelectedEvent_lhewts.second[3]*topSF(ptAntiTopTagged)',
                       'SigWts_murUp'   : 'EvtWeight*EvtWtPV*SelectedEvent_lhewts.second[4]*topSF(ptAntiTopTagged)',
                       'SigWts_murDown'   : 'EvtWeight*EvtWtPV*SelectedEvent_lhewts.second[7]*topSF(ptAntiTopTagged)',
                       #'Cuts'  : 'nAK8>=2 && ptAK8[idxAK8[0]]>500 && ptAK8[idxAK8[1]]>300 && (idxAK8 == idxAK8[0] || idxAK8 == idxAK8[1]) && ht>1100&&(@idxHTagged.size()>0&&@idxAntiHTagged.size()>=0&&@idxTopTagged.size()==0)&&isRegionC&&Max$(abs(etaAK4))>1.5',
                       #'Cuts'  : 'nAK8>=2 && ptAK8[idxAK8[0]]>400 && ptAK8[idxAK8[1]]>300 && (idxAK8[0] == idxHTagged || idxAK8[1] == idxHTagged)  && ht>1100&&isRegionC ',
#                       'Cuts'  : 'nAK8>=2 && ptAK8[idxAK8[0]]>400 && ptAK8[idxAK8[1]]>200 && @idxHTagged.size()>0 && @idxAntiHTagged.size()>=0 && @idxTopTagged.size()>0 && ptTopTagged>400&&(tau3TopTagged/tau2TopTagged)<0.5&&SoftDropMassTopTagged<220&&SoftDropMassTopTagged>=105&&max(sj0CSVTopTagged,sj1CSVTopTagged)<0.460 && dR(etaHTagged,phiHTagged,etaTopTagged,phiTopTagged)>2.0',
                       'Cuts'  : '(ptAK8[0]+ptAK8[1])>850 &&nAK8>=2 && ptAK8[idxAK8[0]]>400 && PrunedMassAK8[0]>50 && isRegionC',
                       'xMin'  : '600',
                       'xMax'  : '2400',
                       'nBins' : '36',
                       'xLabel' : 'M_{T} [GeV]',
                       'yLabel' : 'Events/50GeV',
                       'log'   : True
                     }
            }
isRegionD = {
              'ht' : {
                       'Wts'   : 'EvtWeight*EvtWtPV*btagsf',
                       'Wts_HTUp'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*QuadWeightHT(ht,1)',
                       'Wts_HTDown'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*QuadWeightHT(ht,-1)',
                       'Wts_bcUp'   : 'EvtWeight*EvtWtPV*btagsf_bcUp*topSF(ptTopTagged)*QuadWeightHT(ht,0)',
                       'Wts_bcDown'   : 'EvtWeight*EvtWtPV*btagsf_bcDown*topSF(ptTopTagged)*QuadWeightHT(ht,0)',
                       'Wts_lUp'   : 'EvtWeight*EvtWtPV*btagsf_lUp*topSF(ptTopTagged)*QuadWeightHT(ht,0)',
                       'Wts_lDown'   : 'EvtWeight*EvtWtPV*btagsf_lDown*topSF(ptTopTagged)*QuadWeightHT(ht,0)',
                       'Wts_topSFUp'   : 'EvtWeight*EvtWtPV*topSFUp(ptTopTagged)*QuadWeightHT(ht,0)',
                       'Wts_topSFDown'   : 'EvtWeight*EvtWtPV*topSFDown(ptTopTagged)*QuadWeightHT(ht,0)',
                       'Wts_mufUp'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*QuadWeightHT(ht,0)*SelectedEvent_lhewts.second[2]',
                       'Wts_mufDown'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*QuadWeightHT(ht,0)*SelectedEvent_lhewts.second[3]',
                       'Wts_murUp'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*QuadWeightHT(ht,0)*SelectedEvent_lhewts.second[4]',
                       'Wts_murDown'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*QuadWeightHT(ht,0)*SelectedEvent_lhewts.second[7]',
                       'SigWts' : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)',
                       'SigWts_HTUp'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)',
                       'SigWts_HTDown'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)',
                       'SigWts_bcUp'   : 'EvtWeight*EvtWtPV*btagsf_bcUp*topSF(ptTopTagged)',
                       'SigWts_bcDown'   : 'EvtWeight*EvtWtPV*btagsf_bcDown*topSF(ptTopTagged)',
                       'SigWts_lUp'   : 'EvtWeight*EvtWtPV*btagsf_lUp*topSF(ptTopTagged)',
                       'SigWts_lDown'   : 'EvtWeight*EvtWtPV*btagsf_lDown*topSF(ptTopTagged)',
                       'SigWts_topSFUp'   : 'EvtWeight*EvtWtPV*topSFUp(ptTopTagged)',
                       'SigWts_topSFDown'   : 'EvtWeight*EvtWtPV*topSFDown(ptTopTagged)',
                       'SigWts_mufUp'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*SelectedEvent_lhewts.second[2]',
                       'SigWts_mufDown'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*SelectedEvent_lhewts.second[3]',
                       'SigWts_murUp'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*SelectedEvent_lhewts.second[4]',
                       'SigWts_murDown'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*SelectedEvent_lhewts.second[7]',
                       #'Cuts'  : 'nAK8>=2 && ptAK8[idxAK8[0]]>500 && ptAK8[idxAK8[1]]>300 && (idxAK8 == idxAK8[0] || idxAK8 == idxAK8[1]) && ht>1100&&(@idxHTagged.size()>0&&@idxAntiHTagged.size()>=0&&@idxTopTagged.size()>0&&dR(etaHTagged,phiHTagged,etaTopTagged,phiTopTagged)>2.)&&Max$(abs(etaAK4))>1.5',
                       'Cuts'  : 'nAK8>=2 && ptAK8[idxAK8[0]]>400 && ptAK8[idxAK8[1]]>300 && (idxAK8[0] == idxHTagged && idxAK8[1] == idxTopTagged) || (idxAK8[1] == idxHTagged && idxAK8[0] == idxTopTagged) && ht>1100&&isRegionD ',
                       'xMin'  : '1100',
                       'xMax'  : '3200',
                       'nBins' : '50',
                       'xLabel' : 'H_{T} [GeV]',
                       'yLabel' : 'Events/80GeV',
                       'log'   : True
                     }
            }
isRegionD_mt = {
              'mtprime' : {
                       'Wts'   : 'EvtWeight*EvtWtPV*btagsf',
                       'Wts_HTUp'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*QuadWeightHT(ht,1)',
                       'Wts_HTDown'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*QuadWeightHT(ht,-1)',
                       'Wts_bcUp'   : 'EvtWeight*EvtWtPV*btagsf_bcUp*topSF(ptTopTagged)*QuadWeightHT(ht,0)',
                       'Wts_bcDown'   : 'EvtWeight*EvtWtPV*btagsf_bcDown*topSF(ptTopTagged)*QuadWeightHT(ht,0)',
                       'Wts_lUp'   : 'EvtWeight*EvtWtPV*btagsf_lUp*topSF(ptTopTagged)*QuadWeightHT(ht,0)',
                       'Wts_lDown'   : 'EvtWeight*EvtWtPV*btagsf_lDown*topSF(ptTopTagged)*QuadWeightHT(ht,0)',
                       'Wts_topSFUp'   : 'EvtWeight*EvtWtPV*topSFUp(ptTopTagged)*QuadWeightHT(ht,0)',
                       'Wts_topSFDown'   : 'EvtWeight*EvtWtPV*topSFDown(ptTopTagged)*QuadWeightHT(ht,0)',
                       'Wts_mufUp'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*QuadWeightHT(ht,0)*SelectedEvent_lhewts.second[2]',
                       'Wts_mufDown'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*QuadWeightHT(ht,0)*SelectedEvent_lhewts.second[3]',
                       'Wts_murUp'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*QuadWeightHT(ht,0)*SelectedEvent_lhewts.second[4]',
                       'Wts_murDown'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*QuadWeightHT(ht,0)*SelectedEvent_lhewts.second[7]',
                       'SigWts' : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)',
                       'SigWts_HTUp'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)',
                       'SigWts_HTDown'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)',
                       'SigWts_bcUp'   : 'EvtWeight*EvtWtPV*btagsf_bcUp*topSF(ptTopTagged)',
                       'SigWts_bcDown'   : 'EvtWeight*EvtWtPV*btagsf_bcDown*topSF(ptTopTagged)',
                       'SigWts_lUp'   : 'EvtWeight*EvtWtPV*btagsf_lUp*topSF(ptTopTagged)',
                       'SigWts_lDown'   : 'EvtWeight*EvtWtPV*btagsf_lDown*topSF(ptTopTagged)',
                       'SigWts_topSFUp'   : 'EvtWeight*EvtWtPV*topSFUp(ptTopTagged)',
                       'SigWts_topSFDown'   : 'EvtWeight*EvtWtPV*topSFDown(ptTopTagged)',
                       'SigWts_mufUp'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*SelectedEvent_lhewts.second[2]',
                       'SigWts_mufDown'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*SelectedEvent_lhewts.second[3]',
                       'SigWts_murUp'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*SelectedEvent_lhewts.second[4]',
                       'SigWts_murDown'   : 'EvtWeight*EvtWtPV*topSF(ptTopTagged)*SelectedEvent_lhewts.second[7]',
#                       'Cuts'  : 'nAK8>=2 && ptAK8[idxAK8[0]]>400 && ptAK8[idxAK8[1]]>300 && @idxHTagged.size()>0 && @idxAntiHTagged.size()>=0 && @idxTopTagged.size()>0 && ptTopTagged>400&&(tau3TopTagged/tau2TopTagged)<0.5&&SoftDropMassTopTagged<220&&SoftDropMassTopTagged>=105&&max(sj0CSVTopTagged,sj1CSVTopTagged)>=0.460 && dR(etaHTagged,phiHTagged,etaTopTagged,phiTopTagged)>2.0 ',
                       'Cuts'  : '(ptAK8[0]+ptAK8[1])>850 && nAK8>=2 && ptAK8[idxAK8[0]]>400 && PrunedMassAK8[0]>50 && isRegionD',
                       'xMin'  : '600',
                       'xMax'  : '2400',
                       'nBins' : '36',
                       'xLabel' : 'M_{T} [GeV]',
                       'yLabel' : 'Events/50GeV',
                       'log'   : True
                     }
               }
